services:
  - type: web
    name: wayand-clothing-ecommerce
    env: node
    buildCommand: corepack pnpm install --frozen-lockfile && corepack pnpm build
    startCommand: corepack pnpm start
    envVars:
      - key: NODE_ENV
        value: production
